make Generator.generate partial
mfelsche/ponycheck pull request #37
Opened 2018-05-08 13:43 UTC by mfelsche

and ignore failures up to a configurable number of retries..

So Generators can be more easily created for partial operations.

Also change some Generator combinators and factory methods, most importantly 'one_of' and 'frequency' to not be partial anymore themselves.

2018-05-08 20:51 UTC, Theodus commented
There are conflicts, but they seem straightforward to fix. I'll try to review this tomorrow

2018-05-09 06:56 UTC, mfelsche commented
conflicts resolved

2018-05-10 21:35 UTC, Theodus requested changes
Looks good, other than a few formatting concerns

2018-05-10 21:35 UTC, Theodus commented on examples/custom_class.pony
> +          cuteness_gen.generate_and_shrink(rnd)?
This line should be indented

2018-05-10 21:35 UTC, Theodus commented on ponycheck/test/gen.pony
> +       as WeightedGenerator[U8]:
I think this indentation is off by a space

2018-05-15 19:31 UTC, mfelsche commented
i formatted the mentioned lines. assuming this is good, i am gonna merge.

2018-05-16 21:02 UTC, merged